name: Test, Build and Deploy

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Load firebase_options.dart
        run: echo "$content" > lib/services/firebase_options.dart
        env:
          content: ${{ secrets.FIREBASE_OPTIONS_CONTENT }}

      - name: Check code format
        run: dart format -o none --set-exit-if-changed .

      - name: Static analyzer
        run: flutter analyze --fatal-infos .

      - name: Run unit tests
        run: flutter test test

      - name: Load google-services.json
        run: echo "$content" > android/app/google-services.json
        env:
          content: ${{ secrets.GOOGLE_SERVICES_CONTENT }}

      - name: Build apk
        run: flutter build apk --release --dart-define=API_TOKEN=${{ secrets.API_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: app-release

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.ANDROID_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: app-release.apk