name: Build and Deploy

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 20
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build apk
        run: |
          cat <<< ${{ secrets.GOOGLE_SERVICES_CONTENT }} > ./android/app/google-services.json
          flutter build apk --release

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.ANDROID_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: /build/app/outputs/apk/release/app-release.apk